### ISSUE TITLE
cannot find module 'webpack-cli/bin/config-yargs'

### ISSUE THREAD

**Issue by eunkoo** [eunkoo/piccolo#8]
root@67abe368c444:/app# npm run dev

> frontend@1.0.0 dev /app
> webpack-dev-server --host 0.0.0.0  --inline --progress --config build/webpack.dev.conf.js

module.js:549
    throw err;
    ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/node_modules/webpack-dev-server/bin/webpack-dev-server.js:84:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by eunkoo** [comment]
downgrade webpack-dev-server version

uninstall and install 
webpack-cli 1.5.3
web pack-dev-server 3.0.0
